### ISSUE TITLE
@op annotation doesn't work

### ISSUE THREAD

**Issue by jeffwji** [typelevel/cats#2667]
I'm very like the macro annotations which significantly reduce code. But recently I'm encountering a problem when I tried `@op`, compiler reported exception:

~~~
Error:(8, 6) exception during macro expansion: 
scala.reflect.macros.TypecheckException: not found: type op
	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$3(Typers.scala:32)
	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$2(Typers.scala:26)
	at scala.reflect.macros.contexts.Typers.doTypecheck$1(Typers.scala:25)
	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$7(Typers.scala:38)
	at scala.reflect.internal.Trees.wrappingIntoTerm(Trees.scala:1736)
	at scala.reflect.internal.Trees.wrappingIntoTerm$(Trees.scala:1733)
	at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:18)
	at scala.reflect.macros.contexts.Typers.typecheck(Typers.scala:38)
	at scala.reflect.macros.contexts.Typers.typecheck$(Typers.scala:20)
	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
	at simulacrum.TypeClassMacros.$anonfun$generateTypeClass$5(typeclass.scala:143)
	at simulacrum.TypeClassMacros.$anonfun$generateTypeClass$5$adapted(typeclass.scala:142)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:247)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:246)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:258)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:258)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at simulacrum.TypeClassMacros.filterSimulacrumAnnotations$1(typeclass.scala:142)
	at simulacrum.TypeClassMacros.$anonfun$generateTypeClass$65(typeclass.scala:445)
	at scala.collection.immutable.List.map(List.scala:286)
	at simulacrum.TypeClassMacros.modify$1(typeclass.scala:443)
	at simulacrum.TypeClassMacros.generateTypeClass(typeclass.scala:480)
    @typeclass trait CanAppend[A] {
~~~

The example code below:
~~~
object Example_op {

    import simulacrum._
    @typeclass trait CanAppend[A] {
        @op("|+|") def append(a1: A, a2: A): A
    }

    implicit val intCanAppend: CanAppend[Int] = CanAppend.apply[Int]( { (a1:Int, a2:Int) =>
        { a1 + a2 }
    } )

    import CanAppend.ops._
    val r = 1 |+| 2
}
~~~

`@typeclass` works find! but just `@op` doesn't.  I have `org.scalamacros.paradise` plugin in build.sbt:
~~~
scalacOptions ++= Seq("-Xplugin-require:macroparadise")
addCompilerPlugin("org.scalamacros" %% "paradise" % "2.1.1" cross CrossVersion.full)
~~~

but eventually sbt reached
~~~
[error] Example_3.scala:21:15: value |+| is not a member of Int
[error]     val r = 1 |+| 2
[error]               ^
[error] four errors found
[error] (Compile / compileIncremental) Compilation failed
~~~

Not sure what is missing from there.

**Comment by kailuowang** [comment]
Have you tried to separate your type class definition and your test code into different objects?

**Comment by jeffwji** [comment]
Yes, I tried to separate, but got same error.

**Comment by kubukoz** [comment]
`scalacOptions ++= Seq("-Xplugin-require:macroparadise")`

I think you don't need that. Just having the compiler plugin should be enough.

Also, this isn't a Cats issue, so if you still have problems I recommend you open something in https://github.com/mpilquist/simulacrum :)

**Comment by kubukoz** [comment]
@jeffwji also, please make sure that you enabled the plugin in the sbt project you're using the `op` annotation in, not just in the build's root (if you have subprojects, of course)

**Comment by jeffwji** [comment]
@kubukoz , thanks for reply, I add it to project's build.properties file but still doesn't work..

**Comment by kubukoz** [comment]
Actually, I meant something else. In your build.sbt, if you have a few modules you should have a setup similar to this:

```scala
val commonSettings = Seq(addCompilerPlugin("org.scalamacros" %% "paradise" % "2.1.1" cross CrossVersion.full))

val foo = project in file("foo").settings(commonSettings)
val bar = project in file("bar").settings(commonSettings)

val root = (project in file("."))
  .settings(commonSettings)
  .dependsOn(foo, bar)
  .aggregate(foo, bar)
```

It won't work if you only have 

```scala
addCompilerPlugin("org.scalamacros" %% "paradise" % "2.1.1" cross CrossVersion.full)

val foo = project in file("foo")
val bar = project in file("bar")

val root = (project in file("."))
  .dependsOn(foo, bar)
  .aggregate(foo, bar)
```

.

**Comment by jeffwji** [comment]
I see, but I only have one sub module and I add this plugin under both root and build properties file.

**Comment by jeffwji** [comment]
And it works for @typeclass annotation but just not for this one which is in the typeclass.

**Comment by kubukoz** [comment]
> I see, but I only have one sub module and I add this plugin under both root and build properties file.

The `build.properties` file has nothing to do with plugins ;)

> And it works for @typeclass annotation but just not for this one which is in the typeclass.

This is strange. I suggest asking in simulacrum's repo.

**Comment by ceedubs** [comment]
This doesn't appear to be related to Cats, so I'm going to go ahead and close it out. Please report in the [Simulacrum](https://github.com/mpilquist/simulacrum) repository if you continue to see issues.
