### ISSUE TITLE
Translate the document into Japanese

### ISSUE THREAD

**Issue by shomatan** [typelevel/cats#3116]
Thanks for the great documentation (https://typelevel.org/cats).
I want to translate it into Japanese.
Do you have information on how to contribute?

**Comment by kailuowang** [comment]
That would be fantastic! Thanks the offering. 
The documentation are all here, https://github.com/typelevel/cats/tree/master/docs/src/main/tut
I think you  can start by creating a new folder `locale/jp` in there and place translated files there. Later we can find out how to link to them on our website.

**Comment by shomatan** [comment]
I started to translate. I'm sorry for the delay in timing.

**Comment by kailuowang** [comment]
Thanks very much!

**Comment by shomatan** [comment]
Hi, I'm trying to run `sbt docs/makeMicrosite` on the master branch(latest). But it fails with the following error.

```
[tut] *** Error reported at /Volumes/Dev/cats/docs/src/main/tut/typeclasses/lawtesting.md:45
// <console>:21: warning: match may not be exhaustive.
// It would fail on the following inputs: Leaf, Node(_, _, _)
//            def map[A, B](tree: Tree[A])(f: A => B) = tree match {
//                                                      ^
// error: No warnings can be incurred under -Xfatal-warnings.
[tut] *** Error reported at /Volumes/Dev/cats/docs/src/main/tut/typeclasses/lawtesting.md:48: incomplete input in code block, missing brace or paren?
[tut] *** Error reported at /Volumes/Dev/cats/docs/src/main/tut/typeclasses/lawtesting.md:64: incomplete input in code block, missing brace or paren?
[tut] *** Error reported at /Volumes/Dev/cats/docs/src/main/tut/typeclasses/lawtesting.md:79: incomplete input in code block, missing brace or paren?
[tut] *** Error reported at /Volumes/Dev/cats/docs/src/main/tut/typeclasses/lawtesting.md:106: incomplete input in code block, missing brace or paren?
[tut] *** Error reported at /Volumes/Dev/cats/docs/src/main/tut/typeclasses/lawtesting.md:157: incomplete input in code block, missing brace or paren?
[tut] *** Error reported at /Volumes/Dev/cats/docs/src/main/tut/typeclasses/lawtesting.md:174: incomplete input in code block, missing brace or paren?
[error] (run-main-0) tut.TutException: Tut execution failed.
[error] tut.TutException: Tut execution failed.
[error]         at tut.TutMain$.$anonfun$runl$6(TutMain.scala:17)
[error]         at tut.felix.IO$Compute.loop$1(IO.scala:121)
[error]         at tut.felix.IO$Compute.unsafePerformIO(IO.scala:125)
[error]         at tut.TutMain$.main(TutMain.scala:8)
[error]         at tut.TutMain.main(TutMain.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at sbt.Run.invokeMain(Run.scala:115)
[error]         at sbt.Run.execute$1(Run.scala:79)
[error]         at sbt.Run.$anonfun$runWithLoader$4(Run.scala:92)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:257)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at tut.TutPlugin$.$anonfun$tutOne$1(TutPlugin.scala:149)
[error]         at scala.util.Success.foreach(Try.scala:253)
[error]         at tut.TutPlugin$.tutOne(TutPlugin.scala:149)
[error]         at tut.TutPlugin$.$anonfun$projectSettings$19(TutPlugin.scala:73)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (docs / tut) Nonzero exit code: 1
```

What should I do?
