### ISSUE TITLE
toRightAssociated test failure in CI

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#3568]
Just noticed this test failure in [this job](https://travis-ci.org/github/typelevel/cats/jobs/717834344) for #3567, probably related to #3527:

```
==> X cats.tests.AndThenSuite.toRightAssociated works  0.202s munit.FailException: Failing seed: fSK8i_ADMdWh0P7wdLaXzD1SVThALHwqzii_jRMBtHE=
7051You can reproduce this failure by adding the following override to your suite:
7052
7053  override val scalaCheckInitialSeed = "H6sIq1EUUvxUiPa11mJ4PoKuyBKd3swtk-oTfbaaH6D="
7054
7055Exception raised on property evaluation.
7056> ARG_0: AndThen$201277246
7057> Exception: java.lang.StackOverflowError: null
7058    at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:89)
7059Caused by: java.lang.StackOverflowError
7060    at cats.data.AndThen$Concat.equals(AndThen.scala:163)
7061    at cats.data.AndThen$Concat.equals(AndThen.scala:163)
7062    at cats.data.AndThen$Concat.equals(AndThen.scala:163)
7063    at cats.data.AndThen$Concat.equals(AndThen.scala:163)
```

I don't personally think this should block the next release candidate, but we should look into it. @johnynek, any idea?

**Comment by johnynek** [comment]
I'll try to debug today and send a PR.

**Comment by travisbrown** [comment]
@johnynek Thanks! For what it's worth I spent five minutes trying to reproduce the error locally by setting the seed and the test didn't fail, so it might just be a matter of lower `-Xss` settings or whatever on Travis CI?
