### ISSUE TITLE
`coreJVM/packageSrc` fails with "duplicate entry" error

### ISSUE THREAD

**Issue by SethTisue** [typelevel/cats#4149]
this came up in the Scala 2 community build

```
[error] java.util.zip.ZipException: duplicate entry: cats/instances/package.scala
[error] 	at java.base/java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:241)
[error] 	at java.base/java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:115)
[error] 	at sbt.io.IO$.addFileEntry$1(IO.scala:709)
[error] 	at sbt.io.IO$.$anonfun$writeZip$6(IO.scala:718)
[error] 	at sbt.io.IO$.$anonfun$writeZip$6$adapted(IO.scala:718)
```

**Comment by armanbilge** [comment]
Woops, thanks for the report. If nobody gets to it I'll fix it while working on https://github.com/typelevel/cats/issues/4143.

**Comment by SethTisue** [comment]
scala/community-build@4dfa437efaae687f985fbb9a6eb02d92e4bfeade 👍
